import { Price, Timestamp } from '../value-objects';

export type SignalType = 'BUY' | 'SELL' | 'INVALID';

/**
 * Signal entity: represents a trading signal generated by strategy.
 */
export class Signal {
  private constructor(
    private readonly id: string,
    private readonly type: SignalType,
    private readonly price: Price,
    private readonly time: Timestamp,
    private readonly reason: string,
    private readonly metadata?: Record<string, unknown>,
  ) {}

  /**
   * Factory: create BUY signal
   */
  public static createBuy(
    id: string,
    price: Price,
    time: Timestamp,
    reason: string,
    metadata?: Record<string, unknown>,
  ): Signal {
    return new Signal(id, 'BUY', price, time, reason, metadata);
  }

  /**
   * Factory: create SELL signal
   */
  public static createSell(
    id: string,
    price: Price,
    time: Timestamp,
    reason: string,
    metadata?: Record<string, unknown>,
  ): Signal {
    return new Signal(id, 'SELL', price, time, reason, metadata);
  }

  /**
   * Factory: create INVALID signal
   */
  public static createInvalid(
    id: string,
    price: Price,
    time: Timestamp,
    reason: string,
    metadata?: Record<string, unknown>,
  ): Signal {
    return new Signal(id, 'INVALID', price, time, reason, metadata);
  }

  /**
   * Getters
   */
  public getId(): string {
    return this.id;
  }

  public getType(): SignalType {
    return this.type;
  }

  public getPrice(): Price {
    return this.price;
  }

  public getTime(): Timestamp {
    return this.time;
  }

  public getReason(): string {
    return this.reason;
  }

  public getMetadata(): Record<string, unknown> | undefined {
    return this.metadata;
  }

  /**
   * Serialization
   */
  public toJSON() {
    return {
      id: this.id,
      type: this.type,
      price: this.price.toString(),
      time: this.time.toMsNumber(),
      reason: this.reason,
      metadata: this.metadata ?? null,
    };
  }
}
